baseurl = "http://blog.excareers.com/"

title = "xy1m"
languageCode = "en-us"
paginate = 10
theme = "xy1m"

copyright = "Powered by [Hugo](http://gohugo.io)."
disqusShortname = "excareers"
googleAnalytics = "UA-68632304-1"

[taxonomies]
    category = "categories"
    tag = "tags"
[params]
    keywords = "Algorithms Leetcode Software Engineer"
    description = "About code, thoughts and life"
[author]
    name = "Zhenpeng"
    homepage = "http://xy1m.github.io/"
[sitemap]
  changefreq = "weekly"
  priority = 0.5
[social]
    twitter   = ""
    facebook  = ""
    linkedin  = "zhangzhpeng"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "xy1m"
    gplus     = ""
