baseurl = "http://creazymole.github.io/"
title = "George's playground"
author = "George Zhang"
copyright = "Copyright (c) 2016, George Zhang; all rights reserved."
canonifyurls = true
paginate = 5

[params]
  bio = "George's blog about code,thoughts and life."
  disqusShortname = "excareers" # optional
  toc = true # optional, When set to TRUE this parameter, table of contents appears in all articles.