baseurl = "https://crazymole.github.io/"

title = "Crazy mole"
languageCode = "en-US"
paginate = 10
theme = "heihei"

copyright = "Powered by [Hugo](http://gohugo.io)."
disqusShortname = "excareers"
googleAnalytics = ""

[taxonomies]
    category = "categories"
    tag = "tags"
[params]
    keywords = "Algorithms Leetcode Software Engineer"
    description = "George blog about code, thoughts and life"
[author]
    name = "George Zhang"
    location = "Sunnyvale, CA, USA"
    avatar = "img/coding-mole.gif"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
[social]
    twitter   = ""
    facebook  = ""
    linkedin  = "zhangzhpeng"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "CrazyMole"
    gplus     = ""
