baseurl = "https://crazymole.github.io/"
languageCode = "en-us"
title = "George Playground"
paginate = 5
disqusShortname = "excareers"
theme = "zboots"

[params]
    site_author = "George Zhang"
    site_sitekeywords = "Algorithms Leetcode Software Engineer"
    site_description = "George's blog about code, thoughts and life"
    location = "Waterloo, ON, Canada"
    avatar = "images/coding-mole.gif"
    header_background = "images/cover-coding.jpg"
    header_title = "George Playground"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    google_analytics = ""
[social]
    twitter   = ""
    facebook  = ""
    linkedin  = "zhangzhpeng"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "CrazyMole"
    gplus     = ""
