# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "heihei"
license = "MIT"
licenselink = "https://github.com/CrazyMole/heihei/LICENSE.md"
description = ""
homepage = "http://crazymole.github.io/"
tags = ["pagination", "bootstrap","disqus","responsive","highlight","social"]
features = ["pagination", "bootstrap","disqus","responsive","highlight","social"]
min_version = 0.14

[author]
  name = "George Zhang"
  homepage = "http://crazymole.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
